########################################
# simple-completion-language-server
[language-server.scls]
command = "simple-completion-language-server"

## https://github.com/estin/simple-completion-language-server?tab=readme-ov-file#configure
[language-server.scls.config]
max_completion_items = 20     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"
feature_paths = true          # enable path completion

# Git commit
[[language]]
name = "git-commit"
language-servers = [ "scls" ]
indent = { tab-width = 2, unit = "  " }

# introduce a new language to enable completion on any doc by forcing set language with :set-language stub
[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]
indent = { tab-width = 2, unit = "  " }

########################################
# efm-langserver

[language-server.efm]
command = "efm-langserver"
config = { provideFormatter = true }

########################################
# Elixir

[language-server.lexical]
command = "lexical"
config = { provideFormatter = true }

[[language]]
name = "elixir"
# auto-format = false
language-servers = [ "lexical", "scls" ]
indent = { tab-width = 2, unit = "  " }


########################################
# Markdown

[[language]]
name = "markdown"
# formatter = { command = "markdownlint", args = ["--fix", "-s"] }
language-servers = [ "marksman", "scls", "efm"
  #{ name = "efm", only-features = [ "diagnostics", "format" ] }
  ]
indent = { tab-width = 2, unit = "  " }

########################################
# Nix

[language-server.nil]
command = "nil"
config = { provideFormatter = true }

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
# auto-format = false
language-servers = [ "nil", "scls" ]
indent = { tab-width = 2, unit = "  " }

########################################
# TypeScript

[[language]]
name = "typescript"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] },
  { name = "typescript-language-server", except-features = [ "format" ] }
]
indent = { tab-width = 2, unit = "  " }
