{
  imports = [
    ./sway.nix
    ./wayland-utils.nix
    ./keyring.nix
    ./cursors.nix
    ./dunst.nix
    ./fish.nix
    ./foot.nix
    ./contour.nix
    ./fuzzel.nix
    ./gcolor3.nix
    ./hyprpicker.nix
    ./git.nix
    ./qtwayland.nix
    ./wlay.nix
    ./xdg-desktop-portals.nix
    ./language-servers.nix
  ];
}
